# Generated by Django 3.0.10 on 2021-05-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloud', '0002_devs'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=50)),
                ('project_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
