# Generated by Django 3.0.10 on 2021-05-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycloud', '0003_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='user',
            new_name='owner',
        ),
    ]
