# Generated by Django 3.0.10 on 2021-05-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloud', '0004_auto_20210503_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='devs',
            name='user_sid',
            field=models.BinaryField(default=0),
            preserve_default=False,
        ),
    ]
