# Generated by Django 3.0.10 on 2021-05-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycloud', '0005_devs_user_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devs',
            name='user_sid',
        ),
    ]
