# Generated by Django 3.0.10 on 2021-05-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloud', '0007_devs_user_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='devs',
            name='user_password',
            field=models.BinaryField(default=0),
            preserve_default=False,
        ),
    ]
