# Generated by Django 3.0.10 on 2021-05-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloud', '0008_devs_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='filesize',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='host',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='loc',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='type',
        ),
        migrations.AddField(
            model_name='meta',
            name='data',
            field=models.BinaryField(default=0),
            preserve_default=False,
        ),
    ]
