# Generated by Django 3.0.10 on 2021-06-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloud', '0009_auto_20210517_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='slaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
