# Generated by Django 3.0.10 on 2021-06-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloud', '0010_slaves'),
    ]

    operations = [
        migrations.CreateModel(
            name='storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=50)),
                ('order_id', models.CharField(max_length=50)),
            ],
        ),
    ]
